/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.calcularir;

/**
 *
 * @author aluno
 */
public class FramePrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FramePrincipal
     */
    public FramePrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tfCalcular = new javax.swing.JTextField();
        lbRenda = new javax.swing.JLabel();
        tfValorRenda = new javax.swing.JTextField();
        lbDependentes = new javax.swing.JLabel();
        tfValorDependentes = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfDeducoes = new javax.swing.JTextField();
        btCalcular = new javax.swing.JButton();
        lbRendaAnual = new javax.swing.JLabel();
        lbBaseCalculo = new javax.swing.JLabel();
        lbImposto = new javax.swing.JLabel();
        lbRecebeRenda = new javax.swing.JLabel();
        lbRecebeBase = new javax.swing.JLabel();
        lbRecebeImposto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tfCalcular.setText("Calcular IR");

        lbRenda.setText("Renda Bruta Mensal:");

        lbDependentes.setText("Dependentes:");

        jLabel1.setText("Total Deduções (saúde, educação, etc)");

        btCalcular.setText("Calcular");
        btCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcularActionPerformed(evt);
            }
        });

        lbRendaAnual.setText("Renda Bruta Anual:");

        lbBaseCalculo.setText("Base de Calculo:");

        lbImposto.setText("Imposto Devido:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tfCalcular, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbRenda)
                            .addComponent(tfValorRenda)
                            .addComponent(lbDependentes, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfValorDependentes)
                            .addComponent(jLabel1)
                            .addComponent(tfDeducoes, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lbRendaAnual)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(53, 53, 53)
                                    .addComponent(btCalcular))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(lbRecebeRenda, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addComponent(lbRecebeBase, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbBaseCalculo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbImposto)
                        .addGap(18, 18, 18)
                        .addComponent(lbRecebeImposto)))
                .addContainerGap(167, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tfCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbRenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfValorRenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDependentes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfValorDependentes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfDeducoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btCalcular)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRendaAnual)
                    .addComponent(lbRecebeRenda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBaseCalculo)
                    .addComponent(lbRecebeBase))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbImposto)
                    .addComponent(lbRecebeImposto))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcularActionPerformed
        double valorRenda = calcularRendaBrutaAnual(Integer.parseInt(tfValorRenda.toString()));
        
        double valorDependente = calcularDependente(Integer.parseInt(tfValorDependentes.toString()));
        
        double valorBase = calcularBaseCalculo(valorRenda, valorDependente, Double.parseDouble(tfDeducoes.toString()));
        
        if (valorRenda < 18.000) {
            lbRecebeImposto.setName("0.0");
        } else if (valorRenda > 18.001 && valorRenda < 27.000) {
            double imposto = (valorRenda * 0.15) * 100;
            
            lbRecebeImposto.setName(String.valueOf(imposto));
        } else {
            double valorAplicado = 1.350;
            double imposto = ((valorRenda * 0.28) * 100) + valorAplicado;
            
            lbRecebeImposto.setName(String.valueOf(imposto));
        }
        
        lbRecebeRenda.setName(String.valueOf(valorRenda));
        lbRecebeBase.setName(String.valueOf(valorBase));
        
              
    }//GEN-LAST:event_btCalcularActionPerformed

    private Double calcularBaseCalculo(double valorRenda, double valorDependente, double valorDeducoes) {
        double valorResultado = valorRenda - valorDependente - valorDeducoes;
        
        return valorResultado;
    }
    
    private Double calcularDependente(int qtdDependente) {
        int ano = 12;
        double valorAbatido = 300;
        
        double valorResultado = qtdDependente * valorAbatido * ano;
        
        return valorResultado;
    }
    
    private Double calcularRendaBrutaAnual(int valorRenda) {
        int ano = 12;
        
        double valor = Double.parseDouble(String.valueOf(valorRenda));
        
        double valorResultado = valor * ano;
        
        return valorResultado;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbBaseCalculo;
    private javax.swing.JLabel lbDependentes;
    private javax.swing.JLabel lbImposto;
    private javax.swing.JLabel lbRecebeBase;
    private javax.swing.JLabel lbRecebeImposto;
    private javax.swing.JLabel lbRecebeRenda;
    private javax.swing.JLabel lbRenda;
    private javax.swing.JLabel lbRendaAnual;
    private javax.swing.JTextField tfCalcular;
    private javax.swing.JTextField tfDeducoes;
    private javax.swing.JTextField tfValorDependentes;
    private javax.swing.JTextField tfValorRenda;
    // End of variables declaration//GEN-END:variables
}
